export enum Platform {
  ATARI = 'Atari',
  NINTENDO = 'Nintendo',
  SUPER_NINTENDO = 'Super Nintendo',
  NINTENDO_64 = 'Nintendo 64',
  GAMECUBE = 'GameCube',
  WII = 'Wii',
  WII_U = 'Wii U',
  SWITCH = 'Switch',
  PLAYSTATION_1 = 'PlayStation 1',
  PLAYSTATION_2 = 'PlayStation 2',
  PLAYSTATION_3 = 'PlayStation 3',
  PLAYSTATION_4 = 'PlayStation 4',
  PLAYSTATION_5 = 'PlayStation 5',
  XBOX = 'Xbox',
  XBOX_360 = 'Xbox 360',
  XBOX_ONE = 'Xbox One',
  XBOX_SERIES_X = 'Xbox Series X',
  PC = 'PC',
}

export enum GameGenre {
  ACTION = 'Ação',
  ADVENTURE = 'Aventura',
  RPG = 'RPG',
  FPS = 'FPS First-Person Shooter',
  STRATEGY = 'Estratégia',
  SIMULATION = 'Simulação',
  SPORTS = 'Esportes',
  FIGHTING = 'Luta',
  PUZZLE = 'Puzzle',
  HORROR = 'Horror',
  PLATFORMER = 'Plataforma',
  RACING = 'Corrida',
}
