services:
  frontend:
    container_name: tg-front
    build:
      context: ./tg-frontend
    ports:
      - 80:80
    volumes:
      - ./tg-frontend:/tg-frontend
      - /tg-frontend/node_modules
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:3000
    depends_on:
      - backend

  backend:
    container_name: tg-back
    build: ./tg-backend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /tg-backend
    volumes:
      - ./tg-backend:/tg-backend
      - /tg-backend/node_modules
    depends_on:
      - tg-db
    environment:
      - APP_PORT=3000
      - JWT_SECRET=jwt_secret
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_HOST=tg-db
      - DB_PORT=5432
      - DB_NAME=TrocaGames
      - DATABASE_URL=postgresql://postgres:123456@tg-db:5432/TrocaGames?schema=public

  tg-db:
    image: postgres:latest
    container_name: tg-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: TrocaGames
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - ./database/pg:/data/postgres
