"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const client_1 = require("@prisma/client");
const bcryptjs_1 = require("bcryptjs");
const prisma = new client_1.PrismaClient();
async function main() {
    await prisma.game.deleteMany();
    await prisma.user.deleteMany();
    await prisma.$executeRaw `ALTER SEQUENCE "games_id_seq" RESTART WITH 1;`;
    const user1 = await prisma.user.create({
        data: {
            id: 'userTest-1',
            name: 'test',
            email: 'test@gmail.com',
            password: await (0, bcryptjs_1.hash)('123456', 8),
            deletedAt: null,
        },
    });
    const user2 = await prisma.user.create({
        data: {
            id: 'useTestr-2',
            name: 'test2',
            email: 'test2@gmail.com',
            password: await (0, bcryptjs_1.hash)('123456', 8),
            deletedAt: null,
        },
    });
    await prisma.game.createMany({
        data: [
            {
                title: 'The Legend of Zelda: Breath of the Wild',
                description: 'Aventura em mundo aberto',
                platform: 'Nintendo Switch',
                genre: 'Ação/Aventura',
                price: 59.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Super Mario Odyssey',
                description: 'Plataforma 3D com Mario',
                platform: 'Nintendo Switch',
                genre: 'Plataforma',
                price: 49.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'God of War',
                description: 'A jornada de Kratos e Atreus',
                platform: 'Playstation 4',
                genre: 'Ação',
                price: 39.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Spider-Man',
                description: 'Ação com o Homem-Aranha',
                platform: 'Playstation 4',
                genre: 'Ação/Aventura',
                price: 39.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Red Dead Redemption 2',
                description: 'Velho Oeste imersivo',
                platform: 'Playstation 4',
                genre: 'Ação/Aventura',
                price: 59.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'The Last of Us Part II',
                description: 'A continuação da saga de Ellie',
                platform: 'Playstation 4',
                genre: 'Ação/Aventura',
                price: 49.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Cyberpunk 2077',
                description: 'Futuro distópico em Night City',
                platform: 'PC',
                genre: 'RPG',
                price: 49.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Halo Infinite',
                description: 'Nova era do Master Chief',
                platform: 'Xbox Series X',
                genre: 'FPS',
                price: 59.99,
                forTrade: true,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Elden Ring',
                description: 'Mundo aberto dos criadores de Dark Souls',
                platform: 'PC',
                genre: 'RPG',
                price: 59.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Horizon Forbidden West',
                description: 'A continuação da jornada de Aloy',
                platform: 'Playstation 5',
                genre: 'Ação/Aventura',
                price: 69.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Grand Theft Auto V',
                description: 'O épico de crime de Los Santos',
                platform: 'PC',
                genre: 'Ação',
                price: 29.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: "Assassin's Creed Valhalla",
                description: 'Explore a era viking',
                platform: 'PC',
                genre: 'RPG',
                price: 49.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'FIFA 23',
                description: 'O simulador de futebol definitivo',
                platform: 'Playstation 5',
                genre: 'Esportes',
                price: 69.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'NBA 2K23',
                description: 'O simulador de basquete',
                platform: 'Playstation 5',
                genre: 'Esportes',
                price: 69.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Dark Souls III',
                description: 'O RPG desafiador',
                platform: 'PC',
                genre: 'RPG',
                price: 39.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Sekiro: Shadows Die Twice',
                description: 'Ação e estratégia ninja',
                platform: 'PC',
                genre: 'Ação',
                price: 49.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Monster Hunter: World',
                description: 'Caça monstros épicos',
                platform: 'PC',
                genre: 'RPG',
                price: 29.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Doom Eternal',
                description: 'Destrua demônios sem parar',
                platform: 'PC',
                genre: 'FPS',
                price: 39.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'The Legend of Zelda: Ocarina of Time',
                description: 'Aventura épica no Nintendo 64',
                platform: 'Nintendo 64',
                genre: 'Aventura',
                price: 49.99,
                forTrade: false,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Super Mario 64',
                description: 'O clássico jogo de plataforma 3D',
                platform: 'Nintendo 64',
                genre: 'Plataforma',
                price: 39.99,
                forTrade: true,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Sonic the Hedgehog',
                description: 'O icônico jogo de plataforma do Mega Drive',
                platform: 'Mega Drive',
                genre: 'Plataforma',
                price: 29.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Castlevania: Symphony of the Night',
                description: 'Clássico do gênero Metroidvania',
                platform: 'PlayStation 1',
                genre: 'Ação',
                price: 59.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Final Fantasy VII',
                description: 'Um dos RPGs mais icônicos de todos os tempos',
                platform: 'PlayStation 1',
                genre: 'RPG',
                price: 49.99,
                forTrade: false,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Resident Evil 2',
                description: 'Terror de sobrevivência clássico',
                platform: 'PlayStation 1',
                genre: 'Terror',
                price: 39.99,
                forTrade: true,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Metroid Fusion',
                description: 'Aventura da Samus no GBA',
                platform: 'Game Boy Advance',
                genre: 'Ação',
                price: 34.99,
                forTrade: false,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Pokémon Crystal',
                description: 'Clássico RPG de captura de monstros',
                platform: 'Game Boy Color',
                genre: 'RPG',
                price: 44.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Shenmue',
                description: 'Jogo revolucionário de mundo aberto',
                platform: 'Dreamcast',
                genre: 'Aventura',
                price: 59.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'God of War',
                description: 'Ação mitológica intensa',
                platform: 'PlayStation 2',
                genre: 'Ação',
                price: 39.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Super Mario World',
                description: 'Um clássico jogo de plataforma com Mario e Yoshi.',
                platform: 'Super Nintendo',
                genre: 'Plataforma',
                price: 49.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'The Legend of Zelda: A Link to the Past',
                description: 'Uma aventura épica no reino de Hyrule.',
                platform: 'Super Nintendo',
                genre: 'Ação/Aventura',
                price: 59.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Super Metroid',
                description: 'Um jogo de ação e exploração no planeta Zebes.',
                platform: 'Super Nintendo',
                genre: 'Ação/Aventura',
                price: 54.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Donkey Kong Country',
                description: 'Aventura com Donkey Kong e Diddy Kong.',
                platform: 'Super Nintendo',
                genre: 'Plataforma',
                price: 39.99,
                forTrade: true,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Sonic the Hedgehog 2',
                description: 'Aventura em alta velocidade com Sonic e Tails.',
                platform: 'Mega Drive',
                genre: 'Plataforma',
                price: 29.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Streets of Rage 2',
                description: 'Um clássico beat-em-up com cooperação.',
                platform: 'Mega Drive',
                genre: 'Luta',
                price: 34.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Golden Axe',
                description: 'Aventura medieval com batalhas contra monstros.',
                platform: 'Mega Drive',
                genre: 'Ação',
                price: 24.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Phantasy Star IV',
                description: 'Um RPG clássico com uma história envolvente.',
                platform: 'Mega Drive',
                genre: 'RPG',
                price: 44.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Pokémon Red',
                description: 'Capture e treine Pokémon para se tornar um mestre.',
                platform: 'Game Boy',
                genre: 'RPG',
                price: 49.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: "The Legend of Zelda: Link's Awakening",
                description: 'Aventura de Zelda em um mundo misterioso.',
                platform: 'Game Boy',
                genre: 'Ação/Aventura',
                price: 39.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Tetris',
                description: 'O clássico jogo de quebra-cabeça.',
                platform: 'Game Boy',
                genre: 'Puzzle',
                price: 19.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Super Mario Land',
                description: 'Aventura de Mario no Game Boy.',
                platform: 'Game Boy',
                genre: 'Plataforma',
                price: 29.99,
                forTrade: true,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Pokémon Emerald',
                description: 'Capture e treine Pokémon na região de Hoenn.',
                platform: 'Game Boy Advance',
                genre: 'RPG',
                price: 59.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'The Legend of Zelda: The Minish Cap',
                description: 'Aventura de Zelda com o poder do Minish Cap.',
                platform: 'Game Boy Advance',
                genre: 'Ação/Aventura',
                price: 49.99,
                forTrade: false,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Metroid Fusion',
                description: 'Aventura de Samus em um laboratório espacial.',
                platform: 'Game Boy Advance',
                genre: 'Ação/Aventura',
                price: 44.99,
                forTrade: true,
                images: [],
                ownerId: user1.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
            {
                title: 'Mario Kart: Super Circuit',
                description: 'Corridas clássicas com personagens da Nintendo.',
                platform: 'Game Boy Advance',
                genre: 'Corrida',
                price: 34.99,
                forTrade: true,
                images: [],
                ownerId: user2.id,
                createdAt: new Date(),
                updatedAt: new Date(),
                deletedAt: null,
            },
        ],
    });
    console.log('Seed concluído com sucesso!');
}
main()
    .catch((e) => {
    console.error(e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
//# sourceMappingURL=seed.js.map